<?php

/**
 * Implements hook_menu().
 */
function amengor_custom_menu() {
  $items = array();

  $items['pre-checkout'] = array(
    'title' => 'Checkout',
    'page callback' => 'amengor_custom_pre_checkout',
    'access arguments' => array('access content'),
    'file' => 'amengor_custom.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function amengor_custom_theme($existing, $type, $theme, $path) {
  return array(
    'amengor_custom_register' => array(
      'variables' => array(
        'login' => NULL,
      ),
      'template' => 'templates/login-link'
    ),
  );
}

/**
 * Implements hook_block_info().
 * @see hook_block_info().
 */
function amengor_custom_block_info() {
  $blocks = array();

  $blocks['homepage_category_blocks'] = array(
    'info' => t('Homepage Category Blocks'),
  );
  return $blocks;

}

/**
 * Implements hook_block_view().
 */
function amengor_custom_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'homepage_category_blocks':
      $block['subject'] = '';
      $block['content'] = amengr_custom_homepage_category_blocks();
      break;
  }

  return $block;
}

function amengr_custom_homepage_category_blocks() {
  // Load menu blocks
  $departments = module_invoke('menu', 'block_view', 'menu-departments');
  $collections = module_invoke('menu', 'block_view', 'menu-collections');
  $animals = module_invoke('menu', 'block_view', 'menu-animals');

  $content = '';

  // Departments menu block
  $content .= theme('zsl_custom_theme_blocks', array(
    'block_header' => render($departments['subject']),
    'block_content' => render($departments['content'])
  ));
  // Collections menu block
  $content .= theme('zsl_custom_theme_blocks', array(
    'block_header' => render($collections['subject']),
    'block_content' => render($collections['content'])
  ));
  // Animals menu block
  $content .= theme('zsl_custom_theme_blocks', array(
    'block_last' => TRUE,
    'block_header' => render($animals['subject']),
    'block_content' => render($animals['content'])
  ));


  return theme('zsl_custom_theme_blocks_wrapper', array(
    'content' => $content
  ));


}

/**
 * Implements hook_views_api().
 */
function amengor_custom_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'amengor_custom'),
  );
}

/**
 * Implements hook_form_alter().
 */
function amengor_custom_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#form_id'] == 'commerce_paypal_ec_order_form') {
    $form['paypal_ec']['#access'] = FALSE;
  }
}

/**
 * Perform alterations on an auto-created display node, before it is saved.
 *
 * @param object $node
 *   The initialized display node object, with its product reference field
 *   set to the newly created products.
 */
function amengor_custom_commerce_bpc_display_node_alter(&$node) {
  if(isset($_POST['static_values']['field_gender'])) {
    $node->field_gender[LANGUAGE_NONE][0]['tid'] = $_POST['static_values']['field_gender'][LANGUAGE_NONE];
  }
  if(isset($_POST['static_values']['field_sub_category'])) {
    $node->field_sub_category[LANGUAGE_NONE][0]['tid'] = $_POST['static_values']['field_sub_category'][LANGUAGE_NONE];
  }
}